# Generated by Django 5.2.17 on 2026-08-17 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_corto', models.CharField(blank=True, max_length=255)),
                ('razon_social', models.CharField(blank=True, max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('numero_exterior', models.CharField(blank=True, max_length=50)),
                ('numero_interior', models.CharField(blank=True, max_length=50)),
                ('colonia', models.CharField(blank=True, max_length=255)),
                ('municipio', models.CharField(blank=True, max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(blank=True, max_length=255)),
                ('pais', models.CharField(blank=True, max_length=255)),
                ('cp', models.CharField(blank=True, max_length=20)),
                ('rfc', models.CharField(blank=True, max_length=20)),
                ('tel1', models.CharField(blank=True, max_length=50)),
                ('tel2', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calib_x', models.FloatField(default=45.0)),
                ('calib_y', models.FloatField(default=26.7)),
                ('calib_interlineado', models.FloatField(default=4.1)),
                ('calib_paso', models.FloatField(default=94.7)),
                ('offset_x', models.FloatField(default=0.0)),
                ('offset_y', models.FloatField(default=0.0)),
                ('texto_almacenamiento', models.TextField(blank=True)),
                ('nombre_control_calidad', models.CharField(default='FERNANDO CARDOSO', max_length=255)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuración',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('modelo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('unidad', models.CharField(blank=True, max_length=20)),
                ('cas', models.CharField(blank=True, max_length=50)),
                ('onu', models.CharField(blank=True, max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['modelo'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('folio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('emitido', models.BooleanField(default=False)),
                ('fecha_emision', models.DateTimeField(blank=True, null=True)),
                ('cliente_snapshot', models.JSONField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.cliente')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-folio'],
            },
        ),
        migrations.CreateModel(
            name='RenglonPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unidad', models.CharField(blank=True, max_length=20)),
                ('barriles', models.IntegerField(default=0)),
                ('paquetes', models.IntegerField(default=0)),
                ('lote', models.CharField(blank=True, max_length=100)),
                ('salida', models.CharField(blank=True, max_length=100)),
                ('peso_bruto', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('peso_tara', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('caducidad', models.CharField(blank=True, max_length=100)),
                ('produccion', models.CharField(blank=True, max_length=100)),
                ('especificacion_snapshot', models.JSONField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renglones', to='core.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renglones_pedido', to='core.producto')),
            ],
            options={
                'ordering': ['pedido', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LineaEspecificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('texto', models.CharField(max_length=500)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especificacion', to='core.producto')),
            ],
            options={
                'ordering': ['producto', 'orden'],
                'constraints': [models.UniqueConstraint(fields=('producto', 'orden'), name='unico_producto_orden')],
            },
        ),
        migrations.CreateModel(
            name='ResultadoLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('texto', models.CharField(blank=True, max_length=500)),
                ('renglon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.renglonpedido')),
            ],
            options={
                'ordering': ['renglon', 'orden'],
                'constraints': [models.UniqueConstraint(fields=('renglon', 'orden'), name='unico_renglon_orden')],
            },
        ),
    ]
