# Generated by Django 5.2.17 on 2026-08-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad',
            field=models.CharField(choices=[('KGS.', 'Kilogramos'), ('LTS.', 'Litros')], default='KGS.', max_length=4),
        ),
    ]
