# Generated by Django 5.2.17 on 2026-08-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_normalizar_unidad_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='renglonpedido',
            name='cas',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='renglonpedido',
            name='onu',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
