# Generated by Django 5.2.17 on 2026-08-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_grupos_admin_user'),
    ]

    operations = [
        # El orden importa: 'folio' debe dejar de ser el campo autogenerado
        # (PK) antes de agregar el nuevo 'id' autogenerado, o el estado
        # intermedio tendría dos campos auto a la vez.
        migrations.AlterField(
            model_name='pedido',
            name='folio',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-id']},
        ),
    ]
