# Generated by Django 5.2.17 on 2026-09-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_renglonpedido_barriles'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineaespecificacion',
            name='es_continuacion',
            field=models.BooleanField(default=False, help_text='Es continuación visual de la línea anterior (no lleva su propio resultado).'),
        ),
    ]
