# Generated by Django 5.2.17 on 2026-09-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_normalizar_simbolo_grados'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineaespecificacion',
            name='tipo_continuacion',
            field=models.CharField(blank=True, choices=[('parametros', 'Parámetros (continúa el nombre, ej. "A 25 C:")'), ('especificacion', 'Especificación (continúa el valor, ej. "ALCANFORADO")')], default='parametros', help_text='Solo aplica si es_continuacion está activo: en qué columna del certificado se imprime.', max_length=14),
        ),
    ]
